import os
from typing import List

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from tavily import TavilyClient

load_dotenv()

from langchain.agents import (
    create_agent,  # High-level API to assemble a production-ready agent with tools + LLM
)
from langchain.tools import (
    tool,  # tool decorator: Converts a normal Python function → structured tool definition
)
from langchain_core.messages import (
    HumanMessage,  # Message wrapper representing user input in LangChain’s message schema
)
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_tavily import (
    TavilySearch,  # We use the official TavilyClient for search because it is maintained, more robust, and integrates seamlessly with external APIs,rather than using a custom-built search function which may lack features and ongoing support.
)

GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
if not GOOGLE_API_KEY:
    raise EnvironmentError("GOOGLE_API_KEY not set in environment or .env file")

tavily = TavilyClient()

genai_llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        api_key=GOOGLE_API_KEY,
        temperature=0.2,

)
class SearchInput(BaseModel):
    """
    Input schema for the search tool.

    Attributes:
        query (str): A search query string specifying what you want to look up on the internet.
    """
    query: str = Field(
        ...,
        description=(
            "A search query string specifying what you want to look up on the internet. "
            "Provide a well-structured, clear, and descriptive search query that focuses on the essential details. Avoid vague terms—be specific about people, products, events, or concepts, and include relevant keywords or context to improve search relevance and accuracy."
        ),
    )
    # The Ellipsis (...) indicates this field is required and must be provided by the user.
class Source(BaseModel):
    """
    Schema for a source reference used by the agent.
    Attributes:
        url (str): The direct URL to the external source that the agent referenced or used.
    """
    url: str = Field(
        ...,
        description="Direct URL of the source referenced or utilized by the agent to support or justify its response."
    )

class AgentResponse(BaseModel):
    """
    Represents the response generated by the agent, including its answer and all external sources referenced.

    Attributes:
        answer (str):
            The comprehensive and final answer generated by the agent in response to the provided user query.

        sources (List[Source]):
            A detailed list of external sources that the agent referenced or used to justify and support its answer.
    """
    answer: str = Field(
        ...,
        description=(
            "The final, comprehensive answer provided by the agent in response to the user's query. "
        )
    )
    sources: List[Source] = Field(
        default_factory=list,
        description=(
            "A  list of external sources that the agent referenced or used to justify and support its answer."
        )
    )

@tool(args_schema=SearchInput)
def search(query: str) -> str:
    """
    Perform a real-time web search using the provided query string.

    Args:
        query (str): The specific information, topic, or question to look up on the internet.

    Returns:
        str: A string summarizing the top result(s) for the given query

    Example:
        >>> search("capital of France")
        'The capital of France is Paris.'
    """
    print(f"Searching for: {query}")
    return tavily.search(query=query)


tools = [TavilySearch(),search]
agent = create_agent(model=genai_llm, tools=tools,response_format=AgentResponse)


def main():
    print("Hello from react-search-agent!")
    user_prompt = "search for 3 job postings for an ai engineer using langchain in the bay area on linkedin and list their details"
    response = agent.invoke({
        "messages": [HumanMessage(content=user_prompt)]
    })

    structured_response = response.get("structured_response", None)
    if structured_response:
        print("Structured Agent Response:")
        print(f"Answer:\n{structured_response.answer}\n")
        if structured_response.sources:
            print("Sources:")
            for idx, source in enumerate(structured_response.sources, 1):
                print(f"  {idx}. {str(source)}")
        else:
            print("No sources found in agent response.")
    else:
        print("No structured response returned by agent.")



if __name__ == "__main__":
    main()
