from typing import List

from pydantic import BaseModel, Field


class Source(BaseModel):
    """
    Schema for a source reference used by the agent.
    Attributes:
        url (str): The direct URL to the external source that the agent referenced or used.
    """
    url: str = Field(
        ...,
        description="Direct URL of the source referenced or utilized by the agent to support or justify its response."
    )

class AgentResponse(BaseModel):
    """
    Represents the response generated by the agent, including its answer and all external sources referenced.

    Attributes:
        answer (str):
            The comprehensive and final answer generated by the agent in response to the provided user query.

        sources (List[Source]):
            A detailed list of external sources that the agent referenced or used to justify and support its answer.
    """
    answer: str = Field(
        ...,
        description=(
            "The final, comprehensive answer provided by the agent in response to the user's query. "
        )
    )
    sources: List[Source] = Field(
        default_factory=list,
        description=(
            "A  list of external sources that the agent referenced or used to justify and support its answer."
        )
    )


